// <auto-generated />
using System;
using License_Tracking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace License_Tracking.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250812131500_Week8_AddDealCollaborationActivitiesOnly")]
    partial class Week8_AddDealCollaborationActivitiesOnly
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This is a simplified model builder for the specific migration
            // The full model will be maintained by Entity Framework
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);
        }
    }
}
