using System;
using System.ComponentModel.DataAnnotations;

namespace License_Tracking.Models
{
    public class Report
    {
        [Key]
        public int ReportId { get; set; }

        [Required(ErrorMessage = "Report Type is required")]
        [StringLength(50)]
        public required string ReportType { get; set; } // e.g., CustomerSummary, ProductBusiness

        [Required(ErrorMessage = "Generated Date is required")]
        [DataType(DataType.DateTime)]
        public DateTime GeneratedDate { get; set; }

        [Required(ErrorMessage = "Report Data is required")]
        [StringLength(2000)]
        public required string Data { get; set; } // JSON-serialized report data

        [Required(ErrorMessage = "Generated By Role is required")]
        [StringLength(50)]
        public required string GeneratedByRole { get; set; } // Role that generated the report
    }
}
